name: Docker Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (check only)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: social-media-backend:ci-${{ github.sha }}
          platforms: linux/amd64
